//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RR.Sitecore.AdvancedCache.sitecore.admin.cache {
    
    
    public partial class AdvancedCacheAdmin {
        
        /// <summary>
        /// mainForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm mainForm;
        
        /// <summary>
        /// cacheTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView cacheTabs;
        
        /// <summary>
        /// _GeneralCache control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RR.Sitecore.AdvancedCache.sitecore.admin.cache.UserControls._GeneralCache _GeneralCache;
        
        /// <summary>
        /// viewSiteCaches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewSiteCaches;
        
        /// <summary>
        /// _SiteCaches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RR.Sitecore.AdvancedCache.sitecore.admin.cache.UserControls._SiteCaches _SiteCaches;
        
        /// <summary>
        /// viewDatabaseCaches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewDatabaseCaches;
        
        /// <summary>
        /// _DatabaseCache control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RR.Sitecore.AdvancedCache.sitecore.admin.cache.UserControls._DatabaseCache _DatabaseCache;
        
        /// <summary>
        /// viewAccessResultCaches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewAccessResultCaches;
        
        /// <summary>
        /// viewDataProviderCaches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewDataProviderCaches;
        
        /// <summary>
        /// viewMiscCaches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewMiscCaches;
    }
}
